{% extends "aw_awsim_taskset_00-15.yml" %}
{% block extra_tasks %}
  # Starts ROS tracing
  rosbag:
    commands:
      - "cd $RUNNER_DIR/autoware"
      - "source install/setup.bash"
      - "cd $RUNNER_DIR/scenario_runner"
      - "ros2 bag play --read-ahead-queue-size 50000000 awsim_replay"
    start_deps:
      - collect_sysinfo
{% endblock %}