# Max's Master Thesis, please don't modify!
tasks:
  autoware:
    commands:
      - cd ~/Max_MA/autoware
      - source install/setup.bash
      - ros2 launch autoware_launch e2e_simulator.launch.xml vehicle_model:=sample_vehicle sensor_model:=awsim_sensor_kit map_path:=../map rviz:=False 2>&1 | tee autoware.log
    artifact_location: "~/Max_MA/autoware/autoware.log"
    start_deps:
      - tracing
  trace_cpu_usage:
    commands:
      - top -b -d 0.01 | grep -F '%Cpu(s)' > ~/Max_MA/autoware/cpu_usage.log
    artifact_location: "~/Max_MA/autoware/cpu_usage.log"
    start_debs:
      - autoware
      - tracing
  trace_memory_usage:
    commands:
      - free -s 0.01 > ~/Max_MA/autoware/memory_usage.log
    artifact_location: "~/Max_MA/autoware/memory_usage.log"
    start_debs:
      - autoware
      - tracing
  tracing:
    commands:
      - cd ~/Max_MA/autoware
      - source install/setup.bash
      - rm -rf ~/.ros/tracing/max-ma-trace
      - ros2 trace -s max-ma-trace -k
    artifact_location: "~/.ros/tracing/max-ma-trace"
  runner_logs:
    commands: [ ]
    start_deps:
      - autoware
      - tracing
    artifact_location: "~/Max_MA/scenario_runner/runner.log"
startup:
  commands:
    - pstree -p -s -T -c -a $$
    - pkill -f ros --signal SIGINT
    - timeout 5 tail --pid=$(pgrep -d ' --pid=' -f ros) -f /dev/null || pkill -f ros
    - pgrep -f 'autoware|http\.server|^python3 \./scenario_runner.py' | grep -v -x -F -e $$ -e $PPID | xargs kill
    - echo userspace | sudo tee /sys/devices/system/cpu/cpufreq/policy*/scaling_governor
    - echo 3000000 | sudo tee /sys/devices/system/cpu/cpufreq/policy*/scaling_setspeed
cleanup:
  commands:
    - ros2 topic pub -1 -w 0 /ma_awsim_scenario_runner/shutdown std_msgs/msg/Empty
    - pstree -p -s -T -c -a $$
    - pkill -f ros --signal SIGINT
    - timeout 5 tail --pid=$(pgrep -d ' --pid=' -f ros) -f /dev/null || pkill -f ros
    - pgrep -f 'autoware|http\.server|^python3 \./scenario_runner.py' | grep -v -x -F -e $$ -e $PPID | xargs kill
    - echo ondemand | sudo tee /sys/devices/system/cpu/cpufreq/policy*/scaling_governor
runtime_s: 120
