# Max's Master Thesis, please don't modify!
tasks:
  collect_sysinfo:
    commands:
      - "out_dir=~/Max_MA/scenario_runner/sysinfo"
      - "rm -rf $out_dir"
      - "mkdir $out_dir"
      - "date -u -Iseconds > $out_dir/timestamp.log"
      - "uname -a > $out_dir/uname.log"
      - "env > $out_dir/env.log"
      - "lscpu > $out_dir/lscpu.log"
      - "lspci -vvv > $out_dir/lspci.log"
      - "lsmod > $out_dir/lsmod.log"
      - "numastat > $out_dir/numastat.log"
      - "hostname > $out_dir/hostname.log"
      - "cd ~/edgar/autoware"
      - "vcs custom -n --git --args log --oneline -n 1 > $out_dir/head_commit.log"
      - "vcs status -n > $out_dir/vcs_status.log"
    artifact_location: "~/Max_MA/scenario_runner/sysinfo"
  autoware:
    commands:
      - "cd ~/Max_MA/autoware"
      - "source install/setup.bash"
      - "taskset -c 0-7 ros2 launch autoware_launch e2e_simulator.launch.xml vehicle_model:=sample_vehicle sensor_model:=awsim_sensor_kit map_path:=../map rviz:=False 2>&1 | tee autoware.log"
    artifact_location: "~/Max_MA/autoware/autoware.log"
    start_deps:
      - collect_sysinfo
      - tracing
      - messages
  tracing:
    commands:
      - "cd ~/Max_MA/autoware"
      - "source install/setup.bash"
      - "rm -rf ~/.ros/tracing/max-ma-trace"
      - "ros2 trace -s max-ma-trace -k"
    start_deps:
      - collect_sysinfo
    artifact_location: "~/.ros/tracing/max-ma-trace"
  messages:
    commands:
      - "cd ~/Max_MA/ros2multitopic"
      - "source install/setup.bash"
      - "rm -f messages.h5"
      - "ros2 multitopic bw -o messages.h5 $(cat ../scenario_runner/topics.list | tr '\\n' ' ' | sed 's/ $//')"
    artifact_location: "~/Max_MA/ros2multitopic/messages.h5"
    start_deps:
      - collect_sysinfo
      - tracing
  runner_logs:
    commands: [ ]
    artifact_location: "~/Max_MA/scenario_runner/worker.log"
startup:
  commands:
    - "pstree -p -s -T -c -a $$"
    - "pkill -f ros --signal SIGINT"
    - "timeout 5 tail --pid=$(pgrep -d ' --pid=' -f ros) -f /dev/null || pkill -f ros"
    - "echo userspace | sudo tee /sys/devices/system/cpu/cpufreq/policy*/scaling_governor"
    - "echo $([ "$(uname -i)" = x86_64 ] && echo "3000000" || echo "1500000") | sudo tee /sys/devices/system/cpu/cpufreq/policy*/scaling_setspeed"
cleanup:
  commands:
    - "ros2 topic pub -1 /ma_awsim_scenario_runner/shutdown std_msgs/msg/Empty"
    - "pstree -p -s -T -c -a $$"
    - "pkill -f ros --signal SIGINT"
    - "timeout 5 tail --pid=$(pgrep -d ' --pid=' -f ros) -f /dev/null || pkill -f ros"
    - "echo ondemand | sudo tee /sys/devices/system/cpu/cpufreq/policy*/scaling_governor"
runtime_s: 120
