tasks:
  autoware:
    commands:
      - export ROS_DOMAIN_ID=24
      - source $HOME/edgar/autoware/install/setup.bash
      - export DISPLAY=:1
      - ros2 launch $HOME/edgar/autoware/src/launcher/autoware_launch/autoware_launch/launch/autoware.launch.xml map_path:=$HOME/edgar/op_carla/op_agent/autoware-contents/maps/point_cloud_maps/Town01 vehicle_model:=sample_vehicle sensor_model:=sample_sensor_kit use_sim_time:=true launch_sensing_driver:=false
    artifact_location: "~/edgar/autoware/autoware.log"
    start_deps:
      - tracing
  tracing:
    commands:
      - cd ~/edgar/autoware
      - source install/setup.bash
      - rm -rf ~/.ros/tracing/scenario-trace
      - ros2 trace -s scenario-trace -k
    artifact_location: "~/.ros/tracing/scenario-trace"
startup:
  commands:
    - pkill -x 'top|free'
    - pstree -p -s -T -c -a $$
    - pkill -f ros --signal SIGINT
    - timeout 5 tail --pid=$(pgrep -d ' --pid=' -f ros) -f /dev/null || pkill -f ros
    - pgrep -f 'autoware|http\.server|^python3 \./scenario_runner.py' | grep -v -x -F -e $$ -e $PPID | xargs kill
    - echo userspace | sudo tee /sys/devices/system/cpu/cpufreq/policy*/scaling_governor
    - echo 1500000 | sudo tee /sys/devices/system/cpu/cpufreq/policy*/scaling_setspeed
cleanup:
  commands:
    - pkill -x 'top|free'
    - pstree -p -s -T -c -a $$
    - pkill -f ros --signal SIGINT
    - timeout 5 tail --pid=$(pgrep -d ' --pid=' -f ros) -f /dev/null || pkill -f ros
    - pgrep -f 'autoware|http\.server|^python3 \./scenario_runner.py' | grep -v -x -F -e $$ -e $PPID | xargs kill
    - echo ondemand | sudo tee /sys/devices/system/cpu/cpufreq/policy*/scaling_governor
runtime_s: 80
