tasks:
  autoware:
    start_commands:
      - "cd ~/edgar/autoware"
      - "source install/setup.bash"
      - "export DISPLAY=:1"
      - "ros2 launch autoware_launch logging_simulator.launch.xml map_path:=$PWD/assets/sample-map-rosbag vehicle_model:=sample_vehicle sensor_model:=sample_sensor_kit rviz:=false launch_web_controller:=false | tee autoware.log"
    artifact_location: "~/edgar/autoware/autoware.log"
    start_deps:
      - tracing
  tracing:
    start_commands:
      - "cd ~/edgar/autoware"
      - "source install/setup.bash"
      - "rm -rf ~/.ros/tracing/scenario-trace"
      - "ros2 trace -s scenario-trace -k"
    artifact_location: "~/.ros/tracing/scenario-trace"
  rosbag:
    start_commands:
      - "cd ~/edgar/autoware"
      - "source install/setup.bash"
      - "ros2 bag play assets/sample-rosbag"
    start_deps:
      - autoware
      - tracing
cleanup:
  start_commands:
    - "pkill -f ros"
    - "pkill -f autoware"
    - "pkill -f http.server"
    - "wait $(pgrep -d ' ' -f ros)"
    - "wait $(pgrep -d ' ' -f autoware)"
    - "wait $(pgrep -d ' ' -f http.server)"
runtime_s: 30
