tasks:
  autoware:
    commands:
      - "cd ~/edgar/autoware"
      - "source install/setup.bash"
      - "export DISPLAY=:1"
      - "ros2 launch autoware_launch logging_simulator.launch.xml map_path:=$PWD/assets/sample-map-rosbag vehicle_model:=sample_vehicle sensor_model:=sample_sensor_kit rviz:=false launch_web_controller:=false | tee autoware.log"
    artifact_location: "~/edgar/autoware/autoware.log"
    start_deps:
      - tracing
  tracing:
    commands:
      - "cd ~/edgar/autoware"
      - "source install/setup.bash"
      - "rm -rf ~/.ros/tracing/scenario-trace"
      - "ros2 trace -s scenario-trace -k"
    artifact_location: "~/.ros/tracing/scenario-trace"
  rosbag:
    commands:
      - "cd ~/edgar/autoware"
      - "source install/setup.bash"
      - "ros2 bag play assets/sample-rosbag"
    start_deps:
      - autoware
      - tracing
  runner_logs:
    commands: []
    start_deps:
      - autoware
      - tracing
      - rosbag
    artifact_location: "~/optimization_framework_ws/runner.log"
startup:
  commands:
    - "pkill -f 'ros|autoware|http\\.server'"
    - "tail --pid=$(pgrep -d ' --pid=' -f 'ros|autoware|http\\.server') -f /dev/null"
    - "echo userspace | sudo tee /sys/devices/system/cpu/cpufreq/policy*/scaling_governor"
    - "echo 1500000 | sudo tee /sys/devices/system/cpu/cpufreq/policy*/scaling_setspeed"
cleanup:
  commands:
    - "pkill -f 'ros|autoware|http\\.server'"
    - "tail --pid=$(pgrep -d ' --pid=' -f 'ros|autoware|http\\.server') -f /dev/null"
    - "echo ondemand | sudo tee /sys/devices/system/cpu/cpufreq/policy*/scaling_governor"
runtime_s: 30
